Added tests to BookCollector
tussipbekova/sprint_4 pull request #1
Opened 2023-11-15 17:36 UTC by tussipbekova

2023-11-19 18:00 UTC, kadirovgm requested changes

2023-11-19 18:00 UTC, kadirovgm commented on __pycache__/main.cpython-38.pyc
нужно исправить: эти файлы и папка __pycache__ лишние, их не стоит мержить в общий репозиторий

2023-11-19 18:00 UTC, kadirovgm commented on tests.py
> +    def test_get_book_genre_get_genre(self):
нужно исправить: технически этот тест полностью повторяет предыдущий `test_set_book_genre_set_genre`, хоть ты и ориентируешься на два разных метода

поэтому здесь это излишний тест, который можно и удалить

2023-11-19 18:00 UTC, kadirovgm commented on tests.py
> +        collector.add_new_book('Синий трактор')
можно лучше: чтобы так вручную не добавлять в словарь книги, можно воспользоваться предварительно созданным словарем

2023-11-19 18:00 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('book', ['', 'Бриллиантовая рука Бриллиантовая рука Бриллиантовая рука'])
Отлично! ты правильно пользуешься параметризацией и проверяешь граничные значенения

2023-11-19 18:00 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_books_genre().keys()) == 0
можно лучше: тут можно было обойтись и без keys() так как len() умеет работать и со словарем

2023-11-19 18:00 UTC, kadirovgm commented on tests.py
> +        expected_books = collector.get_books_for_children()
можно лучше: я бы предложил предсоздать словарь с книгами всевозможных жанров, и проверить, что метод get_books_for_children показывает все десткие

2023-11-19 18:00 UTC, kadirovgm commented on tests.py
> +        collector.add_new_book('Три кота')
нужно исправить: так как мы пишем юнит тесты, то нам достаточно проверить один положительный сценарий хотя бы на одном наборе данных, здесь достаточно проверить, что книга добавляется в избранные, поэтому вторую книгу в словарь добавлять нет необходимости - это только увеличивает время прогона теста

2023-11-19 18:00 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('book', ['', 'Бриллиантовая рука Бриллиантовая рука Бриллиантовая рука'])
нужно исправить: давай еще добавим второй тест с параметризацией, которы проверяет условия, при котором книга с таким названием добавится в список, например 1 и 40 симвоолов

2023-11-19 18:00 UTC, kadirovgm commented on tests.py
> +        collector.delete_book_from_favorites('Шантарам')
нужно исправить: достаточно тест написать на одной книге

2023-11-19 18:00 UTC, kadirovgm commented on tests.py
> +        collector.add_book_in_favorites('Гордость и предубеждение')
нужно исправить: достаточно тест написать на двух книгах

2023-11-24 08:30 UTC, tussipbekova commented on __pycache__/main.cpython-38.pyc
это кажется не мой. в develop ветке его нет.

2023-11-25 20:02 UTC, kadirovgm requested changes

2023-11-25 20:02 UTC, kadirovgm commented on tests.py
> +        book_genres = {'Синий трактор':'Мультфильмы','Бриллиантовая рука':'Комедии','Моана':"Мультфильмы"}
нужно исправить: для чего ты создаешь словарь, а потом оттуда забираешь значения и добавляешь в тестируемый словарь? 
это кажется не особо логично так делать, лучше оставить как было

2023-11-25 20:02 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('book', ['Отцы и дети', 'Фауст'])
Нужно исправить: параметризация неправильно применена, тут достаточно проверить тест на одной книге

2023-11-25 20:02 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_books_genre()) == 1
Можно лучше: наличие книги в словаре не гарантирует, что там именна та книга, которую добавили, также можно проверить, что там именно та книга

assert book in collector.get_books_genre() например

2023-11-25 20:02 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('book', ['', 'Бриллиантовая рука Бриллиантовая рука Бриллиантовая рука'])
отлично!

2023-11-25 20:02 UTC, kadirovgm commented on tests.py
> +        assert expected_books == ['Моана']
Можно лучше: а как мы убеждаемся, что остальные детские книги = детские?

2023-11-25 20:02 UTC, kadirovgm commented on tests.py
> +        drakula = book_names[2]
нужно исправить: давай вернем тут как было, такая конструкция бессмысленна, я имел ввиду создать фикстуру с пресозданным словарем book_genres и уже не добавлять книги вручную, а просто гонять тесты на готовом словаре

2023-11-25 20:02 UTC, kadirovgm commented on tests.py
> +        collector.set_book_genre('Шерлок Холмс', 'Детективы')
нужно исправить: мы тестируем add_book_in_favorites, тут выставление жанра ни к чему

2023-11-25 20:02 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('book', ['Отцы и дети', 'Фауст'])
было бы правильно, если бы ты передавала книгу с длиной 1, с длиной 39 и 40 например

2023-11-27 07:16 UTC, kadirovgm approved these changes

2023-12-01 06:26 UTC, merged